// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://anhmdbphbpvoajngywfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuaG1kYnBoYnB2b2Fqbmd5d2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4Njc0MjAsImV4cCI6MjA2ODQ0MzQyMH0.8a58i-kRyVTNoe0q3qxNSSidS_gLsI8iPgxmID8uF0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);